services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/opt/persist/nginx/config:/config
      - /etc/ssl/user:/etc/ssl/user
    ports:
      - 443:443
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.2
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=America/New_York
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.20.0.3

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/20"
