services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/opt/persist/nginx/config:/config
      - /etc/ssl/user:/etc/ssl/user
    ports:
      - 443:443
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.2
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.3

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/20"
